#!/usr/bin/env node
/**
 * Regenerates supabase/seed.sql from the live database.
 *
 * The free tier takes no automatic backups, and maintainers editing in Studio can delete a
 * row with no undo. Running this commits the current state to git, which makes the repo the
 * backup: restoring is running schema.sql then seed.sql.
 *
 * Reads through the anon key, so it can only export what the site itself can see. Votes are
 * deliberately not exported — voter_key is readable by no role, and a tally is a snapshot of
 * an ongoing poll rather than seed data.
 *
 * Usage: npm run backup
 */
import { readFileSync, writeFileSync } from 'node:fs'

function env(key) {
  // .env.local is not loaded outside Next, so read it directly rather than depending on a
  // library just for this script.
  const file = readFileSync('.env.local', 'utf8')
  const match = file.match(new RegExp(`^${key}=(.*)$`, 'm'))
  return process.env[key] || (match ? match[1].trim() : '')
}

const URL_BASE = env('NEXT_PUBLIC_SUPABASE_URL')
const KEY = env('NEXT_PUBLIC_SUPABASE_ANON_KEY')

if (!URL_BASE || !KEY) {
  console.error('Missing NEXT_PUBLIC_SUPABASE_URL / NEXT_PUBLIC_SUPABASE_ANON_KEY')
  process.exit(1)
}

const quote = v => `'${String(v).replace(/'/g, "''")}'`
const nullable = v => (v === null || v === undefined || v === '' ? 'null' : quote(v))
const text = v => quote(v ?? '')
const bool = v => (v ? 'true' : 'false')
const array = v => `array[${(v ?? []).map(quote).join(',')}]::text[]`

async function table(name, query = '') {
  const res = await fetch(`${URL_BASE}/rest/v1/${name}?select=*${query}`, {
    headers: { apikey: KEY, Authorization: `Bearer ${KEY}` },
  })
  if (!res.ok) throw new Error(`${name}: HTTP ${res.status} ${await res.text()}`)
  return res.json()
}

function block(comment, columns, rows, values, conflict, updates) {
  if (rows.length === 0) return `-- ${comment}: no rows\n`
  return [
    `-- ${comment} (${rows.length})`,
    `insert into public.${columns.table} (${columns.list}) values`,
    rows.map(values).join(',\n'),
    `on conflict (${conflict}) do update set`,
    `  ${updates};`,
    '',
  ].join('\n')
}

const [events, leaderboards, hof, polls, options, members] = await Promise.all([
  table('events', '&order=id'),
  table('leaderboards', '&order=id'),
  table('hall_of_fame', '&order=category'),
  table('polls', '&order=created_at'),
  table('poll_options', '&order=poll_id,position'),
  table('members', '&order=position'),
])

const out = [
  `-- DAG seed data, exported from the live database on ${new Date().toISOString().slice(0, 10)}.`,
  '-- Generated by scripts/export-seed.mjs (npm run backup) — do not edit by hand.',
  '-- Run after schema.sql. Safe to re-run: every insert upserts on its key.',
  '--',
  '-- Poll votes are not exported. voter_key is readable by no role, and a live tally is not',
  '-- seed data.',
  '',
  block('events', { table: 'events', list: 'id, event_name, date, description, season, status, event_type, register_url, game_type, recording_url' }, events,
    e => `  (${[nullable(e.id), text(e.event_name), nullable(e.date), text(e.description), text(e.season), text(e.status), text(e.event_type), text(e.register_url), text(e.game_type), nullable(e.recording_url)].join(', ')})`,
    'id',
    'event_name = excluded.event_name, date = excluded.date, description = excluded.description,\n  season = excluded.season, status = excluded.status, event_type = excluded.event_type,\n  register_url = excluded.register_url, game_type = excluded.game_type, recording_url = excluded.recording_url'),

  block('leaderboard rows', { table: 'leaderboards', list: 'id, event_name, season, rank, player_name, points, game_type, team_name' }, leaderboards,
    r => `  (${[nullable(r.id), text(r.event_name), text(r.season), r.rank, text(r.player_name), r.points, text(r.game_type), nullable(r.team_name)].join(', ')})`,
    'id',
    'event_name = excluded.event_name, season = excluded.season, rank = excluded.rank,\n  player_name = excluded.player_name, points = excluded.points,\n  game_type = excluded.game_type, team_name = excluded.team_name'),

  block('hall of fame', { table: 'hall_of_fame', list: 'category, player_name, season, description, game_type' }, hof,
    h => `  (${[text(h.category), text(h.player_name), text(h.season), text(h.description), text(h.game_type)].join(', ')})`,
    'category, season',
    'player_name = excluded.player_name, description = excluded.description, game_type = excluded.game_type'),

  block('polls', { table: 'polls', list: 'id, type, title, description, season, status, ends_at, form_url' }, polls,
    p => `  (${[nullable(p.id), text(p.type), text(p.title), nullable(p.description), text(p.season), text(p.status), nullable(p.ends_at), nullable(p.form_url)].join(', ')})`,
    'id',
    'type = excluded.type, title = excluded.title, description = excluded.description,\n  season = excluded.season, status = excluded.status, ends_at = excluded.ends_at, form_url = excluded.form_url'),

  block('poll options', { table: 'poll_options', list: 'poll_id, id, label, position' }, options,
    o => `  (${[nullable(o.poll_id), nullable(o.id), text(o.label), o.position ?? 0].join(', ')})`,
    'poll_id, id',
    'label = excluded.label, position = excluded.position'),

  block('members', { table: 'members', list: 'name, role, games, is_founder, is_president, note, instagram, discord, position' }, members,
    m => `  (${[text(m.name), text(m.role), array(m.games), bool(m.is_founder), bool(m.is_president), nullable(m.note), nullable(m.instagram), nullable(m.discord), m.position ?? 0].join(', ')})`,
    'name',
    'role = excluded.role, games = excluded.games, is_founder = excluded.is_founder,\n  is_president = excluded.is_president, note = excluded.note,\n  instagram = excluded.instagram, discord = excluded.discord, position = excluded.position'),
].join('\n')

writeFileSync('supabase/seed.sql', out)
console.log(
  `seed.sql written — events ${events.length}, leaderboards ${leaderboards.length}, ` +
    `hall_of_fame ${hof.length}, polls ${polls.length}, options ${options.length}, members ${members.length}`
)
